// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ononwldrcvretdjflyjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ub253bGRyY3ZyZXRkamZseWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMjA5MjIsImV4cCI6MjA2Mzc5NjkyMn0.xPghoGOhPp4e5z0ZGDJe-RClk1hi2hTZDOgBhOXqdnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});